Thread.abort_on_exception = true
